In [1]:
#pip install numpy
import numpy as np


In [3]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [8]:
np.zeros([5,5]) #lista de cinco x cinco elementos igualados a cero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
np.arange(4,20) #[4-20[

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
np.arange(-12,1)

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [22]:
np.arange(0,20,2) #tercer parámetro determina la cantidad del salto de número 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
np.arange(-12,1,0.5)

array([-12. , -11.5, -11. , -10.5, -10. ,  -9.5,  -9. ,  -8.5,  -8. ,
        -7.5,  -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5,
        -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ,   0.5])

In [28]:
arreglo_pares = np.arange(0,20,2)

In [33]:
print(arreglo_pares.size)
print(len(arreglo_pares))
arreglo_tres_dimensiones = np.zeros((2,3,4))
print(arreglo_tres_dimensiones.shape)  #SHAPE sirve para ver la dimensión del arreglo

10
10
(2, 3, 4)


In [35]:
arreglo_pares.shape
arreglo_pares.reshape(10)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
arreglo_pares.reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [37]:
arreglo_pares.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [44]:
arreglos_posibles_combinaciones = np.arange(24)

In [43]:
arreglos_posibles_combinaciones.reshape(1,24)
arreglos_posibles_combinaciones.reshape(24,1)
arreglos_posibles_combinaciones.reshape(6,4)
arreglos_posibles_combinaciones.reshape(4,6)
arreglos_posibles_combinaciones.reshape(8,3)
arreglos_posibles_combinaciones.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [46]:
arreglos_posibles_combinaciones.reshape(24,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [49]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [51]:
#suma
a+b

array([15, 15, 15])

In [52]:
#resta
a-b

array([5, 5, 5])

In [53]:
#multiplicacion
a*b

array([50, 50, 50])

In [55]:
#division
a/b
b/a


array([0.5, 0.5, 0.5])

In [70]:
c = np.arange(30).reshape(2,3,5)

In [71]:
d = np.arange(30).reshape(2,3,5)

In [73]:
#suma con arreglos
c+d

array([[[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28]],

       [[30, 32, 34, 36, 38],
        [40, 42, 44, 46, 48],
        [50, 52, 54, 56, 58]]])

In [75]:
#mod
a%b

array([0, 0, 0], dtype=int32)

In [78]:
#mod
a*10

array([100, 100, 100])

In [80]:
#suma
print(a*10)
#multiplicar
print(a+7)
#resta
print(a-2)
#dividir
print(a/1)
#Mod
print(a%3)

[100 100 100]
[17 17 17]
[8 8 8]
[10. 10. 10.]
[1 1 1]


In [81]:
arreglo_muestra = np.arange(20).reshape(5,2,2)
arreglo_muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [83]:
resp = arreglo_muestra >5
#resp # devuelve booleans
arreglo_muestra[resp] # devuelve los números mayores a 5


array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [130]:
#devol = arreglo_muestra >5 <12 
devol = arreglo_muestra<12
arreglo_muestra[devol]
devol1 = arreglo_muestra>5
arreglo_muestra[devol1]
arreglo_muestra[devol & devol1]

array([ 6,  7,  8,  9, 10, 11])

In [135]:
#>6 <14 y pares
devolucion = (arreglo_muestra<14)& (arreglo_muestra>6)
#devol1 = arreglo_muestra /2
arreglo_muestra[devolucion]

array([ 7,  8,  9, 10, 11, 12, 13])

In [138]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [142]:
B = np.arange(4,8).reshape(2,2)
B

array([[4, 5],
       [6, 7]])

In [144]:
#PRODUCTO PUNTO
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [146]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [148]:
B.dot(A)

array([[10, 19],
       [14, 27]])

In [149]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [150]:
arreglo_doce.sum()

66

In [151]:
arreglo_doce.min()

0

In [152]:
arreglo_doce.max()

11

In [157]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [155]:
arreglo_doce.reshape(3,2,2).sum(axis=0)

array([[12, 15],
       [18, 21]])

In [156]:
arreglo_doce.reshape(3,2,2).sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [158]:
arreglo_doce.reshape(3,2,2).sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])