In [1]:
import numpy as np

In [2]:
arreglo_0_a_90_grados = np.array([0,30,45,60,90])
arreglo_0_a_90_grados

array([ 0, 30, 45, 60, 90])

In [3]:
radianes = arreglo_0_a_90_grados * np.pi / 180 #transformar  a radianes
radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [6]:
np.sin(radianes)  #función seno
np.cos(radianes)  #función coseno
np.tan(radianes)  #función tangente

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [9]:
arreglo_random = np.random.randint(10)  # Genera enteros positivos de [0,10[
arreglo_random

1

In [27]:
arreglo_random = np.random.randint(-1,1)  # Genera enteros negativos de [-1,1[
arreglo_random

-1

In [28]:
arreglo_random = np.random.randint(
    0, #Mínimo
    11, #Máximo
    3 # Cantidad de numeros randómicos
                                  )  
arreglo_random #  [0,11[

array([5, 7, 8])

In [29]:
arreglo_random.mean() # Obtener media

6.666666666666667

In [31]:
np.mean(arreglo_random) 

6.666666666666667

In [50]:
np.var(arreglo_random) 

1.5555555555555554

In [33]:
np.std(arreglo_random) 

1.247219128924647

In [49]:
np.median(arreglo_random) 

7.0